language: node_js
node_js:
  - 17
cache:
  directories:
    - node_modules

before_deploy:
  - "export NODE_OPTIONS=--openssl-legacy-provider"
  - "npm run build"

script: echo "npm test disabled"

install:
  - yarn

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main